### PR TITLE
Feature/Time Tracking

### PR DESCRIPTION
**Pull request by robintoy**
# Feature / Time Tracking

First release / update going from v1.9.14 to v1.10-rc2
### To Do List
- [x] Rebase pull to develop-next (v.1.11.x) as required for feature submission
- [x] Remove the **current time spend** display from post reply and internal note to clean up display
- [x] Remove total from hardware table and make this calculated
- [x] Remove Add time Tab
- [x] Remove total time from ticket table and make this amount calculated on ticket load
- [x] Clean up / remove hardware and place into a new branch
- [x] Clean up comments and other mess ready for commit
### Files modified

include/class.config.php
include/class.nav.php
include/class.thread.php
include/class.ticket.php
include/client/view.inc.php
include/i18n/en_US/help/tips/settings.tickettime.yaml
include/i18n/en_US/list.yaml
include/staff/org-view.inc.php
include/staff/settings-tickettime.inc.php
include/staff/templates/thread-entry.tmpl.php
include/staff/templates/ticket-print.tmpl.php
include/staff/ticket-view.inc.php
scp/org_bill.php
scp/settings.php
scp/tickets.php
scp/tickets_bill.php
scp/tickets_cost.php
### Database Modifications

Run the following commands in something like PHPMyAdmin or MySQL CLI

``` sql
INSERT INTO  ost_list  ( name ,  name_plural ,  sort_mode ,  masks ,  type ,  notes ,  created ,  updated ) VALUES ('Time Type', 'Time Types', 'SortCol', '13', 'time-type', 'Time Spent plugin list, do not modify', NOW(), NOW());
```

``` sql
INSERT INTO `ost_list_items` (`list_id`, `status`, `value`, `sort`)
SELECT ost_list.id, 1, 'Telephone', 1
FROM ost_list
WHERE `name`='Time Type';

INSERT INTO `ost_list_items` (`list_id`, `status`, `value`, `sort`)
SELECT ost_list.id, 1, 'Email', 2
FROM ost_list
WHERE `name`='Time Type';

INSERT INTO `ost_list_items` (`list_id`, `status`, `value`, `sort`)
SELECT ost_list.id, 1, 'Remote', 3
FROM ost_list
WHERE `name`='Time Type';

INSERT INTO `ost_list_items` (`list_id`, `status`, `value`, `sort`)
SELECT ost_list.id, 1, 'Workshop', 4
FROM ost_list
WHERE `name`='Time Type';

INSERT INTO `ost_list_items` (`list_id`, `status`, `value`, `sort`)
SELECT ost_list.id, 1, 'Onsite', 5
FROM ost_list
WHERE `name`='Time Type';
```

``` sql
INSERT INTO  ost_config  (`namespace`, `key`, `value`, `updated`) VALUES
 ('core', 'isclienttime', 0, now()),
 ('core', 'isthreadtime', 0, now()),
 ('core', 'isthreadtimer', 0, now()),
 ('core', 'isthreadbill', 0, now()),
 ('core', 'isthreadbilldefault', 0, now()),
 ('core', 'istickethardware', 0, now());
```

``` sql
ALTER TABLE  ost_thread_entry  ADD COLUMN  time_spent  INT( 11 ) UNSIGNED NOT NULL DEFAULT '0' AFTER  type;

ALTER TABLE  ost_thread_entry  ADD COLUMN  time_type  INT( 11 ) UNSIGNED NOT NULL DEFAULT '0' AFTER  time_spent;

ALTER TABLE  ost_thread_entry  ADD COLUMN  time_bill  INT( 11 ) UNSIGNED NOT NULL DEFAULT '0' AFTER  time_type;
```

### CODE REVIEW

**Comment by greezybacon** [comment]
@robintoy you need to change your text editor to use four spaces instead of a tab

**Comment by robintoy** [comment]
@greezybacon which files are affected??
I'll look at Notepad++ and see what I can do

**Comment by robintoy** [comment]
Going to sound odd by why four spaces instead of tab anyway?

**Comment by robintoy** [comment]
Just doing some testing and first error I get is

Fatal error: Call to a member function isThreadTime() on null in /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/staff/templates/thread-entry.tmpl.php on line 67

Just tracking now what I have missed as the DB is updated and this feature is enabled :( I'll get there!

**Comment by robintoy** [comment]
Ok,
Not sure if I'm nuts here but the code for this is located in /include/class.config.php on line 242 and reads

``` php
function isThreadTime() {
        // determines if Ticket Time via Threads is Enabled
        return ($this->get('isthreadtime'));
    }
```

This code looks perfect as it returns either a 0 or 1 depending if this is enabled or not, which works in the settings menu to turn this on.

Any clues @greezybacon ??

**Comment by kest874** [comment]
image

Settings in notepad + to change

**Comment by robintoy** [comment]
Thanks @kest874
found that, just did not understand why the need

**Comment by greezybacon** [comment]
@robintoy the rest of the code uses four spaces, and tabs are commonly expanded to eight, so it looks inconsistent when viewing. Some files, like YAML expect spaces over tabs.

This should fix your crash

``` patch
diff --git a/include/class.thread.php b/include/class.thread.php
index 199627e..6fbe786 100644
--- a/include/class.thread.php
+++ b/include/class.thread.php
@@ -233,6 +233,7 @@ class Thread extends VerySimpleModel {

     // Render thread
     function render($type=false, $options=array()) {
+        global $cfg;

         $mode = $options['mode'] ?: self::MODE_STAFF;

```

You do not have to add 'customization' comments to your code. Those would be removed when merged into the main project, and git keeps track of your changes. So you don't have to explicitly call them out in the code. Instead, write a line or two as to why your code is necessary, if an explanation would add context when reading the code.

**Comment by robintoy** [comment]
I understand what you mean, at the moment I have added comments everywhere to help me learn the new layout and get back to areas quickly; but I shall remove before this is sent as a pull to osTicket/develop-next

**Comment by robintoy** [comment]
That code did help and seems you run a quick git command to see what was different??

I have been using this link
https://github.com/osTicket/osTicket/compare/develop-next...greezybacon:feature/time-tracking-11

But I now have an issue with the ORM class, but I cannot see you did any changes to that?

Fatal error: Uncaught exception 'OrmException' with message 'ThreadEntry: time_spent: Field not defined' in /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/class.orm.php:311 Stack trace: #0 /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/class.orm.php(631): VerySimpleModel->get('time_spent', NULL) #1 /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/class.orm.php(626): AnnotatedModel->get('time_spent') #2 /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/staff/templates/thread-entry.tmpl.php(68): AnnotatedModel->__get('time_spent') #3 /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/staff/templates/thread-entries.tmpl.php(35): include('/home/hp3-linc1...') #4 /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/class.thread.php(255): include('/home/hp3-linc1...') #5 /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/staff/ticket-view.inc.php(502): Thread->render(Array, Array) #6 /home/hp3-linc1-nfs2-y/53 in /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/class.orm.php on line 311

**Comment by greezybacon** [comment]
@robintoy you probably need to restart Apache / php-fpm

**Comment by robintoy** [comment]
Sorry to be a pain @greezybacon 
I have broken the error into chucks to read it better and it looks like it is all pointing to the field "time_spent" not existing??

```
Fatal error: Uncaught exception 'OrmException' with message 'ThreadEntry: time_spent: Field not defined'
in /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/class.orm.php:311

Stack trace:
#0 /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/class.orm.php(631): VerySimpleModel->get('time_spent', NULL)
#1 /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/class.orm.php(626): AnnotatedModel->get('time_spent')
#2 /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/staff/templates/thread-entry.tmpl.php(68): AnnotatedModel->__get('time_spent')
#3 /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/staff/templates/thread-entries.tmpl.php(35): include('/home/hp3-linc1...')
#4 /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/class.thread.php(255): include('/home/hp3-linc1...')
#5 /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/staff/ticket-view.inc.php(502): Thread->render(Array, Array)
#6 /home/hp3-linc1-nfs2-y/53 in /home/hp3-linc1-nfs2-y/538/531538/user/htdocs/timetracking/include/class.orm.php on line 311
```

**Comment by greezybacon** [comment]
@robintoy did you restart apache / php-fpm/ php dev server / whatever you are using to serve osTicket?

**Comment by robintoy** [comment]
Wish I could, damn hosted system which you cannot restart.

**Comment by greezybacon** [comment]
Change the SECRET_SALT in your config file. You might need to reset the passwords for email addresses after you do that, if you have any.

**Comment by robintoy** [comment]
does that include admin logins etc?

**Comment by greezybacon** [comment]
No. Just email passwords

**Comment by robintoy** [comment]
Salt not help I'm afraid

**Comment by greezybacon** [comment]
Then it must really not exist in your database?

**Comment by robintoy** [comment]
I wish that was true, but looking at my DB in the ost_ticket table I see it
dbexport

**Comment by greezybacon** [comment]
@robintoy you should be looking at the `thread_entry` table

**Comment by robintoy** [comment]
You are so right, I feel such a plank!
I'm guessing my old DB had the fields removed when I upgraded to osTicket v1.10

Running lots of SQL now!

**Comment by robintoy** [comment]
Spotted it!!!
the old table in v1.9.x was ost_ticket_thread which is now replaced with ost_thread_entry

**Comment by robintoy** [comment]
Worked like a charm!!!
Thank you @greezybacon

**Comment by greezybacon** [comment]
No worries. Glad your back on track

**Comment by robintoy** [comment]
I'll get there, just lots have changed from v1.9.x so have been a little lost and out of water; but hopefully I can get this working great and to a level you like as much as the users.

**Comment by greezybacon** [comment]
@robintoy perhaps you'll understand why it's been a slow process to release a "stable" version

**Comment by robintoy** [comment]
@greezybacon I try not to bug and cause issues :)
We have been using v1.10-rc2 almost since release in production and very happy with it; personally I cannot stand jumping back as it very clunky

**Comment by robintoy** [comment]
Hi @greezybacon 
I'm rushing through the changes to get this fully working and just have a question about one of your comments I made into a task.

"Look at changing it from time to expense"

What exactly do you mean with this?

**Comment by greezybacon** [comment]
I think i meant "Look at changing it from `hardware` to `expense`". Not everybody is in the IT industry, but most people interested in this feature would like to track some expenses counted toward a ticket.

**Comment by robintoy** [comment]
That makes sense @greezybacon 

I'm thinking about cleaning up / removing hardware for a moment as that would mean this is complete for time (I believe) and ready for a pull to your system?

Then I was thinking of making a couple more branches: -
- Expenses
- Contracts

where I can work on these sections independently of the time section, I think this sticks more to the way you want to add code and allows us to work towards getting the base time part in the main release.

What you think?

**Comment by greezybacon** [comment]
@robintoy I don't have an immediate problem with that approach. The problem is, this software is downloaded several hundred times a day, and everybody who uses it has a different need for the software. The problem with new features, is that while they have a great following, once they make their way into the software, they will have an even greater following. Then, folks will complain that it doesn't work the way it "obviously should". And that's where things get complicated.

If we add the time tracking by itself, it needs to be quite polished. And it needs to apply to almost any angle someone might want to use it.

So if that's the direction you want to go, finish up your proposal, and I'll review it more specifically.

**Comment by robintoy** [comment]
@greezybacon I was thinking if I get time working fully, just thinking I might look at added an Invoiced field so billed thread information can be marked as invoiced and not appear in later reports then we have hopefully a rather polished system. (This really should be part of contracts and SLAs)

Expenses would then be a great / nice improvement, but as a tab instead of a new window so it is in keeping with your system, and not a hack.

At present most people do not use the hardware as far as I;m aware as they do  not know its there.

I hope the makes sense and makes improvements better for the system, and might allow us to get all in for rc3/4

**Comment by robintoy** [comment]
Hi @greezybacon 
I have been through and done a mass testing and clean up of the code etc....

Cannot see any errors and works smoothly, do you think I'm ready to merge this to our develop-next and then create a pull to your develop-next for review and hopeful inclusion?

**Comment by robintoy** [comment]
Hi @greezybacon 
about to take the plunge and request a pull!

**Comment by kest874** [comment]
Thought I would check this out, I have it working.  Was wondering is there a way to edit time?  

If I have the timer running and walk away and forget and then post a reply it will log the accumulated time.  If I know it's not accurate can I edit it?

**Comment by robintoy** [comment]
Hi @kest874 
Very interesting question and the answer is not 100% simple as I have two possible answers: -
1. Within osTicket = no
2. When using the system is does have a pause button on the timer which you should push before walking away just like locking your workstation so no one else can access your documents, emails etc.

I take your point and is something that would be a good improvement to this once included in the base?

**Comment by kest874** [comment]
I can see someone miss-entering time on accident.  It should require permissions to make an adjustment, and be logged in the thread.

Maybe entertain the ability to put negative minutes in as an alternative.

**Comment by robintoy** [comment]
Final pull to main code of v1.10-rc3 has now been submitted
https://github.com/osTicket/osTicket/pull/3231

**Pull request merged**
